### ISSUE TITLE
eNumPoints

### ISSUE THREAD

**Issue by hymanjd** [lanl/dfnWorks#53]
It looks like modifying eNumPoints isn't working in 2.7. 

Fracture Family order was not changed
Traceback (most recent call last):
  File "/Users/jhyman/src/dfnworks-jdhdev/examples/TPL/TPL_example.py", line 53, in <module>
    DFN.check_input()
  File "/Users/jhyman/.local/lib/python3.9/site-packages/pydfnworks-2.7-py3.9.egg/pydfnworks/dfnGen/generation/input_checking/check_input.py", line 95, in check_input
    self.params = self.write_fracture_families()
  File "/Users/jhyman/.local/lib/python3.9/site-packages/pydfnworks-2.7-py3.9.egg/pydfnworks/dfnGen/generation/input_checking/add_fracture_family_to_params.py", line 29, in write_fracture_families
    add_fracture_family_to_params(self.params, self.fracture_families[i])
  File "/Users/jhyman/.local/lib/python3.9/site-packages/pydfnworks-2.7-py3.9.egg/pydfnworks/dfnGen/generation/input_checking/add_fracture_family_to_params.py", line 115, in add_fracture_family_to_params
    write_value_to_params(params, 'numPoints', fracture_family,
  File "/Users/jhyman/.local/lib/python3.9/site-packages/pydfnworks-2.7-py3.9.egg/pydfnworks/dfnGen/generation/input_checking/add_fracture_family_to_params.py", line 327, in write_value_to_params
    params[fracture_type_prefix + param_key]['value'].append(value)
AttributeError: 'int' object has no attribute 'append'

**Comment by aidanstansberry** [comment]
Got it, I will get to work on this.

**Comment by aidanstansberry** [comment]
Before I go too far down this road, try to add
add_fracture_family(
                                 number_of_points = 8 #(specifies the number of vertices defining the boundary of each fracture. default = 8)

**Comment by hymanjd** [comment]
Well, that worked. Issue closed.
